# LimitRange Reference: https://kubernetes.io/docs/concepts/policy/limit-range/
apiVersion: v1
kind: LimitRange
metadata:
  name: limits
spec:
  limits:
  - max:
      cpu: "300m"
      memory: 1Gi
    type: Container
  - type: PersistentVolumeClaim
    max:
      storage: 2Gi
